# Generated by Django 3.0.8 on 2020-07-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_prizeplace_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование'),
        ),
    ]
