# Generated by Django 3.0.8 on 2020-07-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_auto_20200704_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptioncategory',
            name='text',
            field=models.TextField(unique=True, verbose_name='Текст описания'),
        ),
    ]
