# Generated by Django 3.0.8 on 2020-07-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_auto_20200704_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='descriptioncategory',
            options={'ordering': ['text'], 'verbose_name': 'Описание категории', 'verbose_name_plural': 'Описания категорий'},
        ),
        migrations.AlterModelOptions(
            name='maincategory',
            options={'ordering': ['name'], 'verbose_name': 'Главная категория', 'verbose_name_plural': 'Главные категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Наименование'),
        ),
    ]
