# Generated by Django 3.0.8 on 2020-07-07 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0007_position_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='description', to='reference.DescriptionCategory', verbose_name='Справочник описаний Описание'),
        ),
    ]
