# Generated by Django 3.0.8 on 2020-07-31 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0008_auto_20200707_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='short_name',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Краткое Наименование'),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depatments', to='reference.Faculty', verbose_name='Факультет'),
        ),
    ]
