# Generated by Django 3.1 on 2022-06-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0010_auto_20200806_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст описания')),
                ('show', models.BooleanField(default=False, verbose_name='Отображать баннер?')),
                ('color_text', models.CharField(help_text='https://quasar.dev/style/color-palette#introduction', max_length=50, null=True, verbose_name='Цвет текста')),
                ('color_bg', models.CharField(help_text='https://quasar.dev/style/color-palette#introduction', max_length=50, null=True, verbose_name='Фон баннера')),
                ('icon', models.CharField(help_text='https://materialdesignicons.com/', max_length=50, null=True, verbose_name='Иконка')),
                ('color_icon', models.CharField(help_text='https://quasar.dev/style/color-palette#introduction', max_length=50, null=True, verbose_name='Цвет иконки')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
