# Generated by Django 3.1 on 2023-05-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0011_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
    ]
