version: "3.7"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_DB: ${DOCKER_DB_NAME}
      POSTGRES_USER: ${DOCKER_DB_USER}
      POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
    ports:
      - 5432:5432
  backend:
    image: ${DOCKER_BACKEND_IMAGE}
    command: sh -c "
      poetry run task collectstatic --clear &&
      poetry run task migrate &&
      poetry run task defaultadmin &&
      poetry run task defaultfixtures &&
      poetry run task gunicorn"
    volumes:
      - static:/var/www/app/serve/static
      - media:/var/www/app/serve/media
      - logs:/var/www/app/serve/logs
      - ./.env:/var/www/app/.env
    restart: always
    depends_on:
      - db

  frontend:
    image: ${DOCKER_FRONTEND_IMAGE}
    command: sh -c "quasar serve dist/spa --history -p 3000"
    volumes:
      - ./.env:/var/www/app/.env
    restart: always
    depends_on:
      - backend
  nginx:
    image: nginx:1.17.6-alpine
    volumes:
      - static:/var/www/app/public/static
      - media:/var/www/app/public/media
      - logs:/var/www/app/public/logs
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./robots.txt:/etc/nginx/conf.d/robots.txt
      - ./ssl/certificate.crt:/var/www/app/public/keys/certificate.crt
      - ./ssl/private_key.key:/var/www/app/public/keys/private_key.key
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend

volumes:
  static:
    driver: local
    driver_opts:
      type: none
      device: "${PROJECT_PATH}/${DOCKER_STATIC_DIR}"
      o: bind
  media:
    driver: local
    driver_opts:
      type: none
      device: "${PROJECT_PATH}/${DOCKER_MEDIA_DIR}"
      o: bind
  pg-data:
    driver: local
    driver_opts:
      type: none
      device: "${PROJECT_PATH}/${DOCKER_DB_DIR}"
      o: bind
  logs:
    driver: local
    driver_opts:
      type: none
      device: "${PROJECT_PATH}/${DOCKER_LOG_DIR}"
      o: bind
