# Generated by Django 3.0.8 on 2020-07-04 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_api', '0001_initial'),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_category', models.IntegerField(choices=[(0, 'Функциональность отсутствует'), (1, 'Загрузка документов'), (2, 'Рейтинг'), (3, 'Умножение')], verbose_name='Тип категории')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Весомость показателя')),
            ],
            options={
                'verbose_name': 'Категория Анкеты',
                'verbose_name_plural': 'Категории Анкеты',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.IntegerField(choices=[(1, 'Анкетирование открыто'), (2, 'Анкетирование закончено')], verbose_name='Текстовое представление')),
                ('status', models.IntegerField(choices=[(1, 'Анкетирование открыто'), (2, 'Анкетирование закончено')], verbose_name='Статус анкеты')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questioning.Questionnaire', verbose_name='Анкета')),
                ('user_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_api.UserPosition', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Анкета пользователя',
                'verbose_name_plural': 'Анкеты пользователей',
            },
        ),
        migrations.CreateModel(
            name='MainCategoryQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questioning.Questionnaire', verbose_name='Анкета')),
                ('reference_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.MainCategory', verbose_name='Справочник Категорий')),
            ],
            options={
                'verbose_name': 'Главная Категория Анкеты',
                'verbose_name_plural': 'Главные Категории Анкеты',
            },
        ),
        migrations.CreateModel(
            name='CategoryQuestionnaireUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_point', models.FloatField(blank=True, null=True, verbose_name='Результирующий балл')),
                ('quantity_value', models.FloatField(blank=True, null=True, verbose_name='Количественное значение, введенное пользователем')),
                ('category_questionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questioning.CategoryQuestionnaire', verbose_name='Категория анкеты')),
                ('files', models.ManyToManyField(related_name='catigories_user', to='auth_api.UserFile')),
                ('questionnaire_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questioning.QuestionnaireUser', verbose_name='Анкета пользователя')),
            ],
            options={
                'verbose_name': 'Категория Анкеты  Пользователя',
                'verbose_name_plural': 'Категории Анкеты Пользователей',
            },
        ),
        migrations.AddField(
            model_name='categoryquestionnaire',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questioning.MainCategoryQuestionnaire', verbose_name='Главная категория'),
        ),
        migrations.AddField(
            model_name='categoryquestionnaire',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questioning.CategoryQuestionnaire', verbose_name='Родительская категория'),
        ),
        migrations.AddField(
            model_name='categoryquestionnaire',
            name='periodicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.PeriodicityCategory', verbose_name='Периодичность измерения'),
        ),
        migrations.AddField(
            model_name='categoryquestionnaire',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.Rating', verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='categoryquestionnaire',
            name='reference_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.Category', verbose_name='Справочник Категорий'),
        ),
    ]
