# Generated by Django 3.0.8 on 2020-07-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryquestionnaire',
            name='type_category',
            field=models.IntegerField(choices=[(0, 'Функциональность отсутствует'), (1, 'Загрузка документов'), (2, 'Рейтинг'), (3, 'Ввод числа')], verbose_name='Тип категории'),
        ),
    ]
