# Generated by Django 3.0.8 on 2020-07-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioning', '0002_auto_20200704_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='text',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Текстовое представление'),
        ),
    ]
