# Generated by Django 3.0.8 on 2020-07-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioning', '0003_auto_20200704_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategoryquestionnaire',
            options={'ordering': ['number'], 'verbose_name': 'Главная Категория Анкеты', 'verbose_name_plural': 'Главные Категории Анкеты'},
        ),
        migrations.AddField(
            model_name='categoryquestionnaire',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер категории'),
        ),
        migrations.AddField(
            model_name='maincategoryquestionnaire',
            name='number',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер категории'),
        ),
    ]
