# Generated by Django 3.0.8 on 2020-07-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioning', '0004_auto_20200704_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryquestionnaire',
            name='type_category',
            field=models.IntegerField(blank=True, choices=[(1, 'Загрузка документов'), (2, 'Рейтинг'), (3, 'Ввод числа')], null=True, verbose_name='Тип категории'),
        ),
    ]
