# Generated by Django 3.0.8 on 2020-07-04 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0007_position_short_name'),
        ('questioning', '0005_auto_20200704_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryquestionnaireuser',
            name='prize_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.PrizePlace', verbose_name='Призовое место'),
        ),
    ]
