# Generated by Django 3.0.8 on 2020-07-07 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0008_auto_20200707_1152'),
        ('auth_api', '0002_auto_20200707_1152'),
        ('questioning', '0006_categoryquestionnaireuser_prize_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryquestionnaireuser',
            name='files',
        ),
        migrations.AlterField(
            model_name='categoryquestionnaire',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='questioning.MainCategoryQuestionnaire', verbose_name='Главная категория'),
        ),
        migrations.AlterField(
            model_name='categoryquestionnaire',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childrens', to='questioning.CategoryQuestionnaire', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='maincategoryquestionnaire',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_category', to='questioning.Questionnaire', verbose_name='Анкета'),
        ),
        migrations.AlterField(
            model_name='maincategoryquestionnaire',
            name='reference_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_main_category', to='reference.MainCategory', verbose_name='Справочник Категорий'),
        ),
        migrations.AlterField(
            model_name='questionnaireuser',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire', to='questioning.Questionnaire', verbose_name='Анкета'),
        ),
        migrations.AlterField(
            model_name='questionnaireuser',
            name='user_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_position', to='auth_api.UserPosition', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='FileCategoryQuestionnaireUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.FloatField(blank=True, null=True, verbose_name='Коэффициент соавторства')),
                ('category_questionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questioning.CategoryQuestionnaireUser', verbose_name='Категория анкеты пользователя')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_api.UserFile', verbose_name='файл пользователя')),
            ],
            options={
                'verbose_name': 'Прикрепленный файл',
                'verbose_name_plural': 'Прикрепленные файлы',
            },
        ),
    ]
