# Generated by Django 3.0.8 on 2020-07-10 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questioning', '0008_questionnaire_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecategoryquestionnaireuser',
            name='category_questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='questioning.CategoryQuestionnaireUser', verbose_name='Категория анкеты пользователя'),
        ),
    ]
