# Generated by Django 3.0.8 on 2020-07-10 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0008_auto_20200707_1152'),
        ('questioning', '0009_auto_20200710_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryquestionnaireuser',
            name='prize_place',
        ),
        migrations.RemoveField(
            model_name='categoryquestionnaireuser',
            name='quantity_value',
        ),
        migrations.AddField(
            model_name='filecategoryquestionnaireuser',
            name='prize_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.PrizePlace', verbose_name='Призовое место'),
        ),
        migrations.AddField(
            model_name='filecategoryquestionnaireuser',
            name='quantity_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Количественное значение, введенное пользователем'),
        ),
        migrations.AlterField(
            model_name='categoryquestionnaireuser',
            name='category_questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_questionnaire_user', to='questioning.CategoryQuestionnaire', verbose_name='Категория анкеты'),
        ),
    ]
