# Generated by Django 3.0.8 on 2020-07-13 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0005_auto_20200713_1133'),
        ('questioning', '0010_auto_20200710_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireuser',
            name='user_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_position', to='auth_api.UserPosition', verbose_name='Пользователь'),
        ),
    ]
