# Generated by Django 3.0.8 on 2020-07-16 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0005_auto_20200713_1133'),
        ('questioning', '0011_auto_20200713_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecategoryquestionnaireuser',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth_api.UserFile', verbose_name='файл пользователя'),
        ),
    ]
