# Generated by Django 3.0.8 on 2020-07-21 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0006_auto_20200721_2318'),
        ('questioning', '0012_auto_20200716_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecategoryquestionnaireuser',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_category_questionnaire_user', to='auth_api.UserFile', verbose_name='файл пользователя'),
        ),
    ]
