# Generated by Django 3.0.8 on 2020-07-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioning', '0013_auto_20200721_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryquestionnaireuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Категория прповерена'),
        ),
    ]
