# Generated by Django 3.0.8 on 2020-07-31 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0009_auto_20200731_1410'),
        ('questioning', '0014_categoryquestionnaireuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireuser',
            name='user_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_user', to='auth_api.UserPosition', verbose_name='Пользователь'),
        ),
    ]
