# Generated by Django 3.0.8 on 2020-08-06 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questioning', '0015_auto_20200731_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryquestionnaire',
            options={'ordering': ['number'], 'verbose_name': 'Категория Анкеты', 'verbose_name_plural': 'Категории Анкеты'},
        ),
    ]
