# Generated by Django 3.0.8 on 2020-08-11 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questioning', '0017_categoryquestionnaireuser_result_point_fixed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategoryQuestionnaireUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_point', models.FloatField(blank=True, default=0, null=True, verbose_name='Результирующий балл')),
                ('result_point_fixed', models.FloatField(blank=True, null=True, verbose_name='Исправленный балл')),
                ('main_category_questionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questioning.MainCategoryQuestionnaire', verbose_name='Главная категория анкеты')),
                ('questionnaire_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questioning.QuestionnaireUser', verbose_name='Анкета пользователя')),
            ],
            options={
                'verbose_name': 'Главная категория пользователя',
                'verbose_name_plural': 'Главная категории пользователя',
            },
        ),
    ]
