# Generated by Django 3.0.8 on 2020-08-13 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questioning', '0018_maincategoryquestionnaireuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategoryquestionnaireuser',
            options={'verbose_name': 'Главная категория анкеты пользователя', 'verbose_name_plural': 'Главные категории анкеты пользователя'},
        ),
        migrations.AlterField(
            model_name='categoryquestionnaireuser',
            name='result_point',
            field=models.FloatField(default=0, verbose_name='Результирующий балл'),
        ),
        migrations.AlterField(
            model_name='maincategoryquestionnaireuser',
            name='main_category_questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_category_questionnaire_user', to='questioning.MainCategoryQuestionnaire', verbose_name='Главная категория анкеты'),
        ),
        migrations.AlterField(
            model_name='maincategoryquestionnaireuser',
            name='questionnaire_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_category_questionnaire_user', to='questioning.QuestionnaireUser', verbose_name='Анкета пользователя'),
        ),
    ]
