# Generated by Django 3.1 on 2020-09-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioning', '0019_auto_20200813_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryquestionnaireuser',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True, verbose_name='Категория прповерена'),
        ),
    ]
