# Generated by Django 3.1 on 2021-04-21 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questioning', '0020_auto_20200914_1452'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryquestionnaireuser',
            unique_together={('questionnaire_user', 'category_questionnaire')},
        ),
    ]
