# Generated by Django 3.1 on 2021-04-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0010_auto_20200914_1452'),
        ('questioning', '0021_auto_20210421_1100'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionnaireuser',
            unique_together={('user_position', 'questionnaire')},
        ),
    ]
