# Generated by Django 3.1 on 2021-04-27 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questioning', '0022_auto_20210427_1300'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maincategoryquestionnaireuser',
            unique_together={('main_category_questionnaire', 'questionnaire_user')},
        ),
    ]
