# Generated by Django 3.1 on 2021-05-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioning', '0024_auto_20210526_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryquestionnaireuser',
            name='use_internet_resource_link',
        ),
        migrations.AddField(
            model_name='categoryquestionnaire',
            name='use_internet_resource_link',
            field=models.BooleanField(default=False, verbose_name='Добавить поле для Интернет-ресурса?'),
        ),
    ]
