# Generated by Django 3.1 on 2022-03-09 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0010_auto_20200806_1824'),
        ('questioning', '0027_auto_20220209_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategoryquestionnaire',
            name='reference_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_category', to='reference.maincategory', verbose_name='Справочник Категорий'),
        ),
        migrations.AlterField(
            model_name='maincategoryquestionnaireuser',
            name='main_category_questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_category_questionnaire', to='questioning.maincategoryquestionnaire', verbose_name='Главная категория анкеты'),
        ),
        migrations.AlterField(
            model_name='maincategoryquestionnaireuser',
            name='questionnaire_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_user', to='questioning.questionnaireuser', verbose_name='Анкета пользователя'),
        ),
    ]
