# Generated by Django 3.1 on 2022-03-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioning', '0028_auto_20220309_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='questionnaire/img', verbose_name='Превью'),
        ),
    ]
