# Generated by Django 3.1 on 2022-06-04 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0011_banner'),
        ('questioning', '0029_questionnaire_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryquestionnaire',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='questioning.maincategoryquestionnaire', verbose_name='Главная категория'),
        ),
        migrations.AlterField(
            model_name='categoryquestionnaireuser',
            name='category_questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_questionnaire_user', to='questioning.categoryquestionnaire', verbose_name='Категория анкеты'),
        ),
        migrations.AlterField(
            model_name='categoryquestionnaireuser',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True, verbose_name='Категория проверена?'),
        ),
        migrations.AlterField(
            model_name='maincategoryquestionnaire',
            name='reference_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_main_category', to='reference.maincategory', verbose_name='Справочник Категорий'),
        ),
        migrations.AlterField(
            model_name='maincategoryquestionnaireuser',
            name='main_category_questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_category_questionnaire_user', to='questioning.maincategoryquestionnaire', verbose_name='Главная категория анкеты'),
        ),
        migrations.AlterField(
            model_name='maincategoryquestionnaireuser',
            name='questionnaire_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_category_questionnaire_user', to='questioning.questionnaireuser', verbose_name='Анкета пользователя'),
        ),
    ]
