# Generated by Django 3.1 on 2022-06-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioning', '0030_auto_20220604_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireuser',
            name='effective_contract',
            field=models.BooleanField(blank=True, null=True, verbose_name='Эффективный контракт'),
        ),
    ]
