# Generated by Django 3.1 on 2023-05-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioning', '0031_questionnaireuser_effective_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryquestionnaire',
            name='internet_resource_link_or_doc',
            field=models.BooleanField(default=False, verbose_name='Или ссылка на Интернет-ресурс или документ'),
        ),
        migrations.AlterField(
            model_name='categoryquestionnaire',
            name='use_internet_resource_link',
            field=models.BooleanField(default=False, verbose_name='Добавить поле для Интернет-ресурса'),
        ),
    ]
