# Generated by Django 3.0.8 on 2020-07-07 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0008_auto_20200707_1152'),
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userposition',
            options={'verbose_name': 'Должность пользователя', 'verbose_name_plural': 'Должности пользователей'},
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='coefficient',
        ),
        migrations.AlterField(
            model_name='userposition',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='reference.Department', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position', to='reference.Position', verbose_name='Должность'),
        ),
    ]
