# Generated by Django 3.0.8 on 2020-07-07 09:00

import apps.api.auth.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_auto_20200707_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='date_upload',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(upload_to=apps.api.auth.models.UserFile.user_directory_path, verbose_name='Файл'),
        ),
    ]
