# Generated by Django 3.0.8 on 2020-07-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_auto_20200707_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='type_file',
            field=models.IntegerField(choices=[(0, 'Другое'), (1, 'Ксерокопия'), (2, 'Скриншот'), (3, 'Монография'), (4, 'Публикация'), (5, 'Квартиль'), (6, 'Процентиль'), (7, 'Патент'), (8, 'Свидетельство'), (9, 'Справка'), (10, 'Распоряжение'), (11, 'Приказ'), (12, 'Заявка'), (13, 'Выходные данные'), (14, 'Служебная записка'), (15, 'Справка о внедрении'), (16, 'Диплом'), (17, 'Свидетельство об аккредитации'), (18, 'Грант')], verbose_name='Тип файла'),
        ),
    ]
