# Generated by Django 3.0.8 on 2020-07-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0005_auto_20200713_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_expert',
            field=models.BooleanField(default=False, verbose_name='Эксперт'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_manager_department',
            field=models.BooleanField(default=False, verbose_name='Заведующий кафедры'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_manager_faculty',
            field=models.BooleanField(default=False, verbose_name='Декан факультета'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_super_expert',
            field=models.BooleanField(default=False, verbose_name='Супер эксперт'),
        ),
    ]
