# Generated by Django 3.0.8 on 2020-07-22 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questioning', '0014_categoryquestionnaireuser_is_verified'),
        ('auth_api', '0006_auto_20200721_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questioning.MainCategoryQuestionnaire', verbose_name='Категория эксперта'),
        ),
    ]
