# Generated by Django 3.1 on 2020-09-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0009_auto_20200731_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='type_file',
            field=models.IntegerField(choices=[(0, 'Другое'), (1, 'Ксерокопия'), (2, 'Скриншот'), (3, 'Монография'), (4, 'Публикация'), (5, 'Квартиль'), (6, 'Процентиль'), (7, 'Патент'), (8, 'Свидетельство'), (9, 'Справка'), (10, 'Распоряжение'), (11, 'Приказ'), (12, 'Заявка'), (13, 'Выходные данные'), (14, 'Служебная записка'), (15, 'Справка о внедрении'), (16, 'Диплом'), (17, 'Свидетельство об аккредитации'), (18, 'Грант'), (19, 'Сертификат'), (20, 'Грамота'), (21, 'Удостоверение')], verbose_name='Тип файла'),
        ),
    ]
