# Generated by Django 3.1 on 2021-12-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0011_auto_20211216_1708'),
        ('auth_api', '0011_auto_20211216_1710'),
    ]

    operations = [
    ]
