# Generated by Django 3.1 on 2022-01-24 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0012_merge_20211216_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='date_upload',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
