# Generated by Django 3.1 on 2022-03-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0014_auto_20220209_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='user/img', verbose_name='Фотография пользователя'),
        ),
    ]
