# Generated by Django 3.1 on 2023-05-23 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0017_applicationsubmission_applicationsubmissionposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsubmissionposition',
            name='application_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_submission_position', to='auth_api.applicationsubmission', verbose_name='Пользователь'),
        ),
    ]
